### ISSUE TITLE
Delete Imported Folder Too?

### ISSUE THREAD

**Issue by budimanjojo** [davidnewhall/unpackerr#121]
Hello, first of all thank you for this awesome tool, I got a lot of archived downloads and this really helps me a lot :)

Everything works as expected until now, but I realized the folder.delete_after doesn't delete the imported folder after 5m (only the files) and I ended up with a lot of empty folders in my download folder. Why is the folder not also be deleted with the files? Thank you.

**Comment by davidnewhall** [comment]
If you set `move_back` to `false` it should delete the folder too. Can you share your `folder` config?

**Comment by budimanjojo** [comment]
> If you set `move_back` to `false` it should delete the folder too. Can you share your `folder` config?
I don't modify move_back, so it should be defaulted to false right?
I'm using kubernetes and here are the environment variables:
```
apiVersion: v1
kind: Secret
metadata:
  name: unpackerr-secrets
  labels:
    app.kubernetes.io/name: unpackerr
type: Opaque
stringData:
  UN_SONARR_0_URL: http://sonarr-svc.default.svc.cluster.local:8989
  UN_SONARR_0_API_KEY: secret
  UN_SONARR_0_PATHS_0: /downloads/Completed
  UN_RADARR_0_URL: http://radarr-svc.default.svc.cluster.local:7878
  UN_RADARR_0_API_KEY: secret
  UN_RADARR_0_PATHS_0: /downloads/Completed
  UN_LIDARR_0_URL: http://lidarr-svc.default.svc.cluster.local:8686
  UN_LIDARR_0_API_KEY: secret
  UN_LIDARR_0_PATHS_0: /downloads/Completed
  UN_FOLDER_0_PATH: /downloads/Completed
```
