### ISSUE TITLE
Undefined folder being Scanned

### ISSUE THREAD

**Issue by vmcosco** [davidnewhall/unpackerr#166]
I have Unpackerr running via docker-compose.  Below is my compose file.  You can see that I have separate download locations (/tv, /movies, /music and /books) defined in my compose file.  The Unpackerr log is showing that it is finding archives in "/data/wip/media_donwloads/complete/tv_archive".  Why is Unpackerr checking this location if it is not defined?  Do I have something setup incorrectly?  I do not have any applications defined in .conf.

``` 
 unpackerr:
    image: cr.hotio.dev/hotio/unpackerr
    container_name: unpackerr
    restart: always
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.184
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/appdata/unpackerr:/config
      - wip:/data/wip
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # Sonarr Config
      - UN_SONARR_0_URL=http://192.168.90.151:8989
      - UN_SONARR_0_API_KEY=$SONARR_API_KEY
      - UN_SONARR_0_PATHS_0=/data/wip/media_downloads/complete/tv
      - UN_SONARR_0_PROTOCOLS=torrent,usenet
      # Radarr Config
      - UN_RADARR_0_URL=http://192.168.90.152:7878
      - UN_RADARR_0_API_KEY=$RADARR_API_KEY
      - UN_RADARR_0_PATHS_0=/data/wip/media_downloads/complete/movies
      - UN_RADARR_0_PROTOCOLS=torrent,usenet
      # Lidarr Config
      - UN_LIDARR_0_URL=http://192.168.90.153:8686
      - UN_LIDARR_0_API_KEY=$LIDARR_API_KEY
      - UN_LIDARR_0_PATHS_0=/data/wip/media_downloads/complete/music
      - UN_LIDARR_0_PROTOCOLS=torrent,usenet
      # Readarr Config
      - UN_READARR_0_URL=http://192.168.90.155:8787
      - UN_READARR_0_API_KEY=$READARR_API_KEY
      - UN_READARR_0_PATHS_0=/data/wip/media_downloads/complete/books
      - UN_READARR_0_PROTOCOLS=torrent,usenet
```
