### ISSUE TITLE
Unpackerr stuck in restart loop

### ISSUE THREAD

**Issue by Njinx** [davidnewhall/unpackerr#193]
Hello, I'm having an issue where Unpackerr restarts exactly one minute after booting. I'm deploying this via Portainer.

### docker-compose
```yaml
###Unpackerr docker-compose.yml Example
###See https://github.com/davidnewhall/unpackerr#readme for variable descriptions and options
version: "3"
services:

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    network_mode: bridge
    volumes:
      # You need at least this one volume mapped so Unapckerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - /mnt/media-storage/torrent-downloads:/downloads
      - /mnt/media-storage/unpackerr-logs:/logs
    restart: unless-stopped
    user: 1000:1000
    # What you see below are defaults. You only need to include things you change.
    environment:

      # General config
      - UN_DEBUG=true
      - UN_LOG_FILE=/logs/unpackerr.log
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      # Sonarr Config
      - UN_SONARR_0_URL=http://10.0.0.52:8989
      - UN_SONARR_0_API_KEY=[SONARR_KEY]
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=-1
      # Radarr Config
      - UN_RADARR_0_URL=http://10.0.0.52:7878
      - UN_RADARR_0_API_KEY=[RADARR_KEY]
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=-1
    security_opt:
      - no-new-privileges:true
```

### `docker container ls | grep unpackerr`
```
bb16c2d73bdd   golift/unpackerr                               "/image"                 10 minutes ago   Restarting (1) 17 seconds ago                                                                                                                                                                                unpackerr
```

### `uname -a`
```
Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
```

### Log file
Completely empty :(
