### ISSUE TITLE
File Permissions / PUID PGID - Synology Docker

### ISSUE THREAD

**Issue by DrFrankensteinUK** [davidnewhall/unpackerr#213]
Hey, I recently set this up and wanted to confirm the correct method for passing file permissions. 

I used the compose example as the basis for my own which is below, I am using the config file separately also posted below. However two issues/questions?

The example compose uses the below
`user: ${PUID}:${PGID}`
I entered my own IDs 
`user: 1031:100`

However, when starting up the container it then filled in two environment variables mapped to 1000:1000 which immediately stopped the container as it was unable to write to the config folder as this user does not exist.

So I then passed in the PUID and PGID via environment variables which seems to be working as no errors reading the config file. As I am struggling to find a release in the arrs that requires unpacking, I set up a watched folder to test out.

"/data/torrents/unrarme" which extracts to "/data/torrents/unrarme/complete"

However if I drop a linuxiso.rar into that folder it errors with 

`folder.go:343: [DEBUG] Folder: Ignored File Event: /data/torrents/unrarme/LinuxISO.rar (unreadable)`, 

Both the folder and file are owned by the same docker user that has exclusive access to /date and /docker with no other file permission issues, which leads me to believe I am passing something across incorrectly. 

Where am I going wrong?

Snippet from the compose with the original user section commented out.

```
  unpackerr:
    container_name: unpackerr
    image: cr.hotio.dev/hotio/unpackerr
#    user: 1031:100
    environment:
      - TZ=Europe/London
      - PUID=1031
      - PGID=100
      - UMASK-002
    volumes:
      - /volume3/docker/unpackerr:/config
      - /volume1/data:/data
``````

Config pasted here https://paste.drfrankenstein.co.uk/paste/?3e3db9bfbf457137#CTX4AF7rbcJ59btBF98kSFBcTEA6epcXzWvVfwhBsqjz
