### ISSUE TITLE
Exception when adding Radarr v0.2 server

### ISSUE THREAD

**Issue by Kareltje1980** [davidnewhall/unpackerr#59]
Hi, 

I add a Radarr instance using a docker-compose file. It crashes:

```
Attaching to unpacker
unpacker    | 2020/10/30 22:32:12.067834 start.go:98: Unpackerr v0.7.1-199 Starting! (PID: 1) 2020-10-30 22:32:12.067646648 +0100 CET m=+0.006950408
unpacker    | 2020/10/30 22:32:12.067939 logs.go:104: ==> Startup Settings <==
unpacker    | 2020/10/30 22:32:12.068082 sonarr.go:40:  => Sonarr Config: 0 servers
unpacker    | panic: runtime error: index out of range [0] with length 0
unpacker    |
unpacker    | goroutine 18 [running]:
unpacker    | github.com/davidnewhall/unpackerr/unpacker.(*Unpackerr).logRadarr(0xc0000c0180)
unpacker    |   /unpackerr/unpacker/radarr.go:38 +0x52e
unpacker    | github.com/davidnewhall/unpackerr/unpacker.(*Unpackerr).logAppStartupInfo(0xc0000c0180)
unpacker    |   /unpackerr/unpacker/apps.go:62 +0x39
unpacker    | github.com/davidnewhall/unpackerr/unpacker.(*Unpackerr).logStartupInfo(0xc0000c0180)
unpacker    |   /unpackerr/unpacker/logs.go:105 +0x8d
unpacker    | github.com/davidnewhall/unpackerr/unpacker.(*Unpackerr).Run(0xc0000c0180)
unpacker    |   /unpackerr/unpacker/start.go:138 +0xb3
unpacker    | created by github.com/davidnewhall/unpackerr/unpacker.Start
unpacker    |   /unpackerr/unpacker/start.go:107 +0x6ee
unpacker exited with code 2
```

this happens when using the following data compose file:
```
version: "3.8"
services:
  unpacker:
    image: golift/unpackerr
    container_name: unpacker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - UN_RADARR_0_URL=https://sonarr.<removed>
      - UN_RADARR_0_API_KEY=<removed>
      - UN_DEBUG=True
    volumes:
      - /home/data/downloads/qBittorrent:/downloads
    restart: unless-stopped
```

The weird thing is that if I use the UN_SONARR variables it does not crash?
